server:
  port: 8040
spring:
  application:
    # 注册到nacos上的服务名称
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 发现nacos上其他服务组件
          enabled: true
      routes:
        - id: after_route
          uri: lb://user-center
          predicates:
            - TimeBetween=上午9:00,下午10:00
          filters:
            - PreLog=mike,mhm

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always